#!/usr/bin/env bash
# ==============================================================================
# STEP 0 — ONBOARDING AN EXISTING PROJECT (BROWNFIELD)
# Index the existing codebase + generate a baseline as a reference for Impact Analysis (Step 2).
# DO NOT touch the target project's source — only read & generate docs into docs/specs/_baseline/.
#   bash .agent/scripts/onboard-existing.sh [source-path, default: .]
# ==============================================================================
set -u

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
# By default index the entire workspace/ (where the project source lives). You can pass a specific path: workspace/<project-name>
SRC="${1:-$ROOT/workspace}"
BASELINE_DIR="$ROOT/docs/specs/_baseline"
mkdir -p "$BASELINE_DIR"

echo "🔎 [Step 0] Onboarding existing project. Source: $SRC"

# 1. Index with Graphify (if available) — real CLI verb is 'update <path>'
if command -v graphify &>/dev/null; then
  echo "🧠 Graphify index (graphify update)..."
  ( cd "$SRC" && graphify update . --no-cluster ) || echo "  ⚠️ graphify update failed (skipping)."
else
  echo "  ⚠️ 'graphify' CLI not found — skipping index. Run install-all-plugins.sh (pip install graphifyy)."
fi

# 2. Index with GitNexus (if available)
if command -v gitnexus &>/dev/null; then
  echo "🧠 GitNexus analyze..."
  ( cd "$SRC" && gitnexus analyze ) || echo "  ⚠️ gitnexus analyze failed (skipping)."
elif command -v npx &>/dev/null; then
  echo "🧠 GitNexus via npx analyze..."
  ( cd "$SRC" && npx -y gitnexus analyze ) || echo "  ⚠️ npx gitnexus analyze failed (skipping)."
else
  echo "  ⚠️ 'gitnexus' CLI / npx not found — skipping."
fi

# 3. Generate the current-state baseline (a skeleton for the AI Agent to fill in)
BASELINE_FILE="$BASELINE_DIR/README.md"
if [ ! -f "$BASELINE_FILE" ]; then
  {
    echo "# BASELINE — Project current state (brownfield)"
    echo ""
    echo "> Auto-generated by onboard-existing.sh. The AI Agent fills in/cross-checks in Steps 1-2."
    echo ""
    echo "## High-level directory tree"
    echo '```text'
    ( cd "$SRC" && find . -maxdepth 2 -type d \
        -not -path './.git*' -not -path './node_modules*' -not -path './.agent*' \
        | sort | head -100 )
    echo '```'
    echo ""
    echo "## Detected languages / manifests"
    for f in package.json composer.json requirements.txt pyproject.toml go.mod pom.xml build.gradle Gemfile Cargo.toml; do
      [ -f "$SRC/$f" ] && echo "- \`$f\`"
    done
    echo ""
    echo "## Follow-up work for the AI Agent"
    echo "- [ ] Summarize the architecture & main modules into docs/specs/_baseline/."
    echo "- [ ] Record implicit ADRs (existing architecture decisions) into docs/adr/."
    echo "- [ ] Identify the entry point for the first change request → run /discovery."
  } > "$BASELINE_FILE"
  echo "📄 Baseline created: $BASELINE_FILE"
else
  echo "📄 Baseline already exists: $BASELINE_FILE (left unchanged)."
fi

echo "✅ Onboarding done. Next: run the workflow from Step 1 (/discovery) for the first change request."
